# Generated by Django 3.2.8 on 2021-10-26 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_rename_artist_music_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='name',
            new_name='artist',
        ),
    ]
