# Generated by Django 3.2.6 on 2021-09-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burgerking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='burgerking',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
