# Generated by Django 3.2.8 on 2021-10-29 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_review_actors'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MAM',
        ),
    ]
